'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Login
    
    '''<summary>
    '''tb_username control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_username As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rfv_noUsername control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfv_noUsername As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''tb_password control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_password As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rfv_noPassword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfv_noPassword As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''b_Login control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents b_Login As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''l_Incorrect control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents l_Incorrect As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''h_register control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents h_register As Global.System.Web.UI.WebControls.HyperLink
End Class
