'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Map
    
    '''<summary>
    '''tb_Start control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_Start As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lb_noStart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lb_noStart As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tb_End control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_End As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''b_AddDestination control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents b_AddDestination As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''P_Dest_cont control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P_Dest_cont As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''tb_DestNum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_DestNum As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lb_toomany control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lb_toomany As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''b_RouteCalc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents b_RouteCalc As Global.System.Web.UI.WebControls.Button
End Class
