'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Map

    '''<summary>
    '''tb_Start control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_Start As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rfv_noStart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfv_noStart As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''tb_End control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_End As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''b_AddDestination control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents b_AddDestination As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''b_LessDestination control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents b_LessDestination As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''l_destinations control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents l_destinations As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''p_routenodes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents p_routenodes As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''b_RouteCalc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents b_RouteCalc As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''tb_URL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_URL As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tb_Distance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_Distance As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tb_Duration control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_Duration As Global.System.Web.UI.WebControls.TextBox
End Class
