'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Register
    
    '''<summary>
    '''tb_fname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_fname As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rfv_fname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfv_fname As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''tb_lname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_lname As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rfv_lname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfv_lname As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''tb_uname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_uname As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rfv_username control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfv_username As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''l_username control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents l_username As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tb_password control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_password As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rfv_password control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfv_password As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''l_passwordlength control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents l_passwordlength As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tb_passwordmatch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_passwordmatch As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rfv_passwordMatch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfv_passwordMatch As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''l_passwordmatch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents l_passwordmatch As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tb_email control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_email As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rfv_email control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfv_email As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''l_email control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents l_email As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tb_vehiclemake control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_vehiclemake As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rfv_vehicleMake control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfv_vehicleMake As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''tb_vehiclemodel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_vehiclemodel As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rfv_vehicleModel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfv_vehicleModel As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''tb_vehicleage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_vehicleage As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rfv_vehicleage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfv_vehicleage As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''tb_license control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_license As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rfv_license control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfv_license As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''l_license control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents l_license As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tb_lastMOT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_lastMOT As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rfv_lastMOT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfv_lastMOT As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''tb_nextMOT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_nextMOT As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rfv_nextMOT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfv_nextMOT As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''b_Register control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents b_Register As Global.System.Web.UI.WebControls.Button
End Class
